### ISSUE TITLE
Request for Backup option

### ISSUE THREAD

**Issue by psichic** [note-space/recordando#1]
I have been using recordando for a few days and I find it quite interesting and aligned to my needs. It would be nicer if the notes could be backed up to folders and text files within folders in a zip file for offline storage.

**Comment by note-space** [comment]
Hello and thanks for your interest in the program.  I'm thinking that there are two parts to your suggestion.  The first is about making a backup of the notes, which I think is best done by copying the sqlite file to a USB drive or some other location.  The second is to get the notes out of the sqlite file and into text files, for some other reason, such as to make them editable by any text editor.  I am certainly open to that idea .. the program could be re-coded to read/write to text files (in folders), and not use sqlite at all.

**Comment by note-space** [comment]
OK, I have added a function to make a backup .. it backs up all the notes into a single html file .. this keeps the presentation and the organization in the backup the same as what is in the program.
I am marking this issue as closed.
Please let me know when you give it a try, and if it works for you, or not.
thanks .. Tom

**Comment by psichic** [comment]
Thank you ver much for taking the time to address the issue. I would check
it out and reply back.
Thanks again
Regards,
Shibaji

**Comment by psichic** [comment]
I have tried out the backup option today - unzipped the new distribution
and copied the old db file to app, keeping other files unchanged. Then used
the menu/backup option and checked out the notes_2021-03-29.htm file
generated in app. The generated file is perfect and much better than a flat
file database. Thank you very much for implementing my request.

Thanks, Regards and Best Wishes
Shibaji
